### ISSUE TITLE
Duda sobre un valor conveniente para demostración.

### ISSUE THREAD

**Issue by SrGarZito** [IIC1253/IIC1253-2024-2#15]
**¡Buenas tardes!**

Si yo tengo un l > m >= 1, ¿Puedo tomar un 'm' **conveniente** dentro del conjunto que yo planteo según mi HI y, de esa forma, poder llegar a la solución a partir de mi HI?
¿Quedaría demostrado?

**¡Esperaré pacientemente la respuesta!**
♦️♣️ **_¡Saludos Cordiales!_** ♠️♥️

**Comment by rocimarquez** [comment]
Hola! No te entiendo muy bien si esa "l" es la del enunciado u otra letra parte de tu HI donde defines tu conjunto. Si me pudieras dar más info te podría ayudar mejor :)

**Comment by SrGarZito** [comment]
**¡Claro!**

Como no sé muy bien cuanto puedo decir de mi respuesta lo deje un poco ambiguo en mi primera _Issue_, esa "l" es del enunciado porque estoy aplicando la inducción a raíz de ella. La letra 'm' (en mi tarea la tengo puesta como phi) es aquella letra con un conjunto que yo he definido.

♣️♦️ **¡Esperaré nuevamente la respuesta!** ♠️♥️
