### ISSUE TITLE
Inducción fuerte

### ISSUE THREAD

**Issue by FranVvi** [IIC1253/IIC1253-2024-2#17]
Hola, quería consultar acerca de la definición específica que se debe utilizar sobre la inducción fuerte.
En el PPT de la clase, la hipótesis de inducción (HI) es que P(k) es verdadera para todo k<n, por lo tanto, P(n) es verdadera. Sin embargo, en el libro de la bibliografía del curso aparece que k≤n, por lo que P(n+1) sería verdadera.
Yo utilicé la segunda definición, pero no estoy segura si es necesario utilizar específicamente la que aparece en el PPT.

**Comment by tremendapithon** [comment]
Yo tengo entendido que son lo mismo, ya que en una asumes para k < n y demuestras para n, y en la otra definición asumes para k <= n, y demuestras para n+1. A la final la idea es demostrar para el siguiente número de lo que asumiste en tu HI.
