### ISSUE TITLE
Duda sobre el sentido de $x_{hi}$

### ISSUE THREAD

**Issue by Gilbertacus** [IIC1253/IIC1253-2024-2#25]
No entiendo muy bien si tiene o no sentido las variables $x_{hi}$: De acuerdo con el enunciado, $x_{hi}$ es que la persona i sea la persona h en el núcleo, sin embargo, ¿esto no implicaría que la definición de $x_{hi}$ ya hay un núcleo? Por ejemplo consideremos $V=\{1,2\}$ y $E=\{\}$, aquí, las variables $x_{hi}$ no tienen sentido debido a que no hay un núcleo, así que no podemos hablar de estas variables, y por ende, cualquier fórmula que utilice estas variables no tendría sentido si no hay núcleos, pero necesitamos usar estas variables en nuestras respuestas. ¿Cómo deberíamos interpretar $x_{hi}$ sin dar el contexto de un núcleo?

**Comment by oliviallanosj** [comment]
Hola! Si te fijas, la variable x_hi no implica directamente que exista un núcleo, sino que, en el caso que hubiera, la persona i ocupa la h-ésima posición en un posible núcleo. Por ende, toma el valor verdadero si esto pasa, y falso si no es posible. Por ende, no necesariamente debe existir un núcleo.

**Comment by Mikson16** [comment]
Efectivamente hay casos donde no existe un núcleo y por ende las variables pierden sentido; sin embargo, debes observar que en la pregunta se pide que la fórmula que determines $\phi$ debe cumplir con la propiedad enunciada "*Existe un núcleo con k personas para V y E  **si y solo si** phi es satisfacible*".

**Comment by Gilbertacus** [comment]
Entiendo lo que hay que hacer con "\phi", sin embargo de acuerdo con el enunciado $\phi$ debe utilizar las variables $x_{hi}$, y no me queda claro como podría hacer una fórmula proposicional con variables sin sentido. ¿Hay algún ejemplo (tal vez, de un tema completamente distinto para que no den hints de la tarea) en donde se defina una fórmula con variables que no tengan sentido?

**Comment by Mikson16** [comment]
Supongamos que un entrenador Pokémon está en una batalla, sea el conjunto B de 0 a m, que contiene a todos los Pokémon que pueden batallar y D el conjunto de 0 a m de todos los Pokémon que no pueden batallar y T el conjunto de 0 a n que contiene a todos los Pokémon del entrenador, sea la variable proposicional $x_{ij}$, donde i representa que el Pokémon pertenece al conjunto T y j pertenece al conjunto B y la variable proposicional $p_{ik}$ donde k pertenece al conjunto de los Pokémon que no pueden batallar, entonces: que formula proposicional $\phi$ usando las variables proposicionales representan que el entrenador puede seguir batallando si un Pokémon puede batallar y no está en el conjunto de derrotados, para simplificar bajémoslo a un puro caso $\phi =  x_{ij} \land \lnot p_{ik}$ Entonces siempre y cuando el Pokémon se encuentre en el conjunto de Pokémon del entrenador, en el conjunto de los Pokémon batallantes y no este en el conjunto de derrotados, $\phi$ será satisfacido y el entrenador podrá seguir batallando.

La variable proposicional ayudan a representar, en este caso, un estado de verdadero o falso, con el fin de generar una fórmula lógica que represente la proposición que buscamos.

Espero que el ejemplo te haya ayudado :D

**Comment by Gilbertacus** [comment]
i.e. si un subíndice o una variable (en este caso, los $p_{ik}$) no tuviera sentido, ¿se interpreta como falsa? De ser así, creo que entiendo. Muchas gracias por el ejemplo.

**Comment by Mikson16** [comment]
¡Buenas noches!
Asumo que cuando te refieres a que no tiene sentido es porque en tu formulación dicha variable siempre será falsa, recuerda que una variable proposicional puede tomar valores de verdad verdadero y falso, sin embargo, ten en cuenta que en tu formulación *deben* aparecer las variables $p_{ij}$ y $x_{hi}$.

 ¡Saludos!
