### ISSUE TITLE
Duda con escala de puntaje (T1)

### ISSUE THREAD

**Issue by SrGarZito** [IIC1253/IIC1253-2024-2#47]
¡Buenas tardes!

Esta duda radica en preguntar como funciona la escala de puntaje para revisar la T1.
Al principio pensé que se trataba de que cada punto de los 12 totales valía 0.5 décimas pero, al sumar mi total de puntaje, llegaba a una nota mayor a la que se me ha sido asignada, por ende, quiero saber la escala para poder identificar si fue un error administrativo la nota actual que tengo o si es que la escala es distinta.

_¡Esperaré pacientemente la respuesta!_
♠️♥️ _**¡Saludos!**_ ♦️♣️

**Comment by cicarrasco5** [comment]
Hola!
La escala es al 50% de exigencia considerando el promedio de ambas preguntas con nota mínima 1,0. Como cada pregunta suma 6 puntos la nota de cada pregunta es PTJE + 1, luego la nota es el promedio de las dos notas considerando cualquier descuento por formato u otro problema.
Espero quede claro y cualquier problema puedes escribirme a cicarrasco5@uc.cl o esperar al módulo de recorrección.
