### ISSUE TITLE
Duda definición parte b)

### ISSUE THREAD

**Issue by Gilbertacus** [IIC1253/IIC1253-2024-2#87]
En la pregunta 1.b), ¿Cuál sería una forma aceptable de definir un grafo? Pregunto porque mi ejemplo considera al menos 10 vértices, y varias aristas, así que quisiera saber si tengo que dar la definición conjuntista del grafo o basta dibujarlo con Tikz.

**Comment by ChupeteBecker** [comment]
En vista de que un grafo es una tupla (V, E), podrías definirlo con los conjuntos de vértices y aristas, pero si eso queda muy desordenado por el tamaño de los conjuntos, puedes dibujar el grafo con la librería tikz. Por otra parte, si no te sientes cómodo con la definición del grafo, asegurate de explicar bien el grafo para que se pueda entender la explicación de la propiedad mas adelante.

Saludos!

**Comment by Gilbertacus** [comment]
Gracias por la aclaración.
